# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: '.env'
      displayName: Download secure file

    - script: |
        echo Downloaded $(env.secureFilePath)
        mv $(env.secureFilePath) $(System.DefaultWorkingDirectory)
      displayName: Move .env to Working Directory

    - script: |
        docker-compose build
        docker login -u swsaturn -p $(DOCKER_HUB_PWD)
        docker push swsaturn/$(imageName)
      displayName: docker-compose build